using Microsoft.Data.Sqlite;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using POIneer.Render.Domain.Models;
using POIneer.Render.Infrastructure.FileSystem;
using POIneer.Render.Infrastructure.Sqlite;
using Xunit;
using Xunit.Abstractions;

namespace POIneer.Render.IntegrationTests.Infrastructure.Sqlite;

public sealed class SqlitePoiRepositoryTests(ITestOutputHelper output)
{
    private readonly ITestOutputHelper _output = output;

    [Fact]
    public async Task AddAndList_ReturnsInsertedPoi()
    {
        var logger = new XunitLogger<SqlitePoiRepositoryTests>(_output);
        logger.LogInformation("Starting SqlitePoiRepositoryTests.AddAndList_ReturnsInsertedPoi test.");

        // Arrange
        var tempDirOptions = Options.Create(new TempOptions
        {
            RootFolderName = "poineer-tests",
            KeepOnDispose = false
        });

        ITemporaryDirectoryFactory tempDirectoryFactory =
            new TemporaryDirectoryFactory(tempDirOptions);

        await using var tempDir = tempDirectoryFactory.Create("sqlite-poi-repository-tests");

        var root = tempDir.DirectoryPath;
        var dbPath = Path.Combine(root, $"{Guid.NewGuid():N}.sqlite");
        var cs = new SqliteConnectionStringBuilder
        {
            DataSource = dbPath,
            Pooling = false
        }.ToString();

        await using (var con = new SqliteConnection(cs))
        {
            await con.OpenAsync();

            var cmd = con.CreateCommand();
            cmd.CommandText = """
                CREATE TABLE poi (
                    id              INTEGER PRIMARY KEY,
                    osm_id          INTEGER NOT NULL,
                    name            TEXT,
                    amenity         TEXT,
                    latitude        REAL NOT NULL,
                    longitude       REAL NOT NULL
                );
               """;
            await cmd.ExecuteNonQueryAsync();
        }
        var sut = CreateSut(dbPath);

        var osmId = 5678L;
        var location = new GeoPoint(Latitude: 52.5200, Longitude: 13.4050);

        // Act
        await sut.AddAsync(new Poi(
            Id: 0, // Id will be auto-generated by the database
            OsmId: osmId,
            Name: "Test POI",
            Amenity: "cafe",
            Location: location
        ), CancellationToken.None);

        var all = (await sut.GetAllAsync(100, CancellationToken.None)).ToList();

        // Assert
        var poi = Assert.Single(all);
        Assert.True(poi.Id > 0);
        Assert.Equal(osmId, poi.OsmId);
        Assert.Equal("Test POI", poi.Name);
        Assert.Equal("cafe", poi.Amenity);
        Assert.Equal(location.Latitude, poi.Location.Latitude);
        Assert.Equal(location.Longitude, poi.Location.Longitude);
    }

    private static SqlitePoiRepository CreateSut(string dbPath) => new SqlitePoiRepository(() =>
    {
        var cs = new SqliteConnectionStringBuilder
        {
            DataSource = dbPath,
            Pooling = false
        }.ToString();

        return new SqliteConnection(cs);
    });
}
