<Project>
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

 <!-- Non-test projects: collect coverage -->
  <PropertyGroup Condition="'$(IsTestProject)' != 'true'">
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
  </PropertyGroup>

  <!-- Test projects: no self-coverage -->
  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <CollectCoverage>false</CollectCoverage>
  </PropertyGroup>

  <!-- Exclude boilerplate / generated code from coverage -->
  <ItemGroup Condition="'$(IsTestProject)' != 'true'">
    <ExcludeByFile Include="
      **/Program.cs;
      **/*Dto.cs;
      **/*Migrations/*.cs;
      **/*Designer.cs;
      **/*.g.cs;
      **/*.generated.cs
    " />
  </ItemGroup>

</Project>
