flyway.url=jdbc:sqlite:output/poi.sqlite
flyway.user=
flyway.password=

# Relative to the location of this configuration file
flyway.locations=filesystem:migrations/sql/poi

# Flyway settings
flyway.cleanDisabled=false
flyway.baselineOnMigrate=true
